### ISSUE TITLE
Weather description wraps to next option

### ISSUE THREAD

**Issue by marymkelly** [Gogi4aaa/Strats#1]
On vertical carousel, weather description bleeds into next option

![Screenshot 2024-05-19 at 7 36 35 PM](https://github.com/Gogi4aaa/Strats/assets/8996968/90491576-ae56-4812-9bd4-82f7935a9844)

**Comment by cruckman900** [comment]
fixed issue by increasing the size of the slide to 10.5rem (was 9rem).
I need a second set of eyes on my code as it has a duplicate handleClick method in 2 files that I feel could be reduced, but without them in both places currently, the disable button feature doesn't work.
